name: supabase_offline_sync
description: An offline-first sync toolkit for Supabase — sync local Hive storage with Supabase tables automatically, with conflict resolution and connectivity-aware auto-sync.
version: 1.0.0
repository: https://github.com/hk994512/supabase_offline_syncs

environment:
  sdk: ^3.12.2

dependencies:
  supabase: ^2.16.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.3.1
  flutter_test:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.5
  test: ^1.25.6
